In [19]:
#data pre processing
#rescaling data between 0 & 1
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] # col names
dataframe = read_csv(filename, names = names)
array = dataframe.values

#now we sepearate array into input and output components
X = array[:, 0:8]
Y = array[8, :]
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(X)

#summarrize the transformed data
set_printoptions(precision = 2)
print(rescaledX[0:5,:])


[[ 0.35  0.74  0.59  0.35  0.    0.5   0.23  0.48]
 [ 0.06  0.43  0.54  0.29  0.    0.4   0.12  0.17]
 [ 0.47  0.92  0.52  0.    0.    0.35  0.25  0.18]
 [ 0.06  0.45  0.54  0.23  0.11  0.42  0.04  0.  ]
 [ 0.    0.69  0.33  0.35  0.2   0.64  0.94  0.2 ]]


In [34]:
#Standardizing data to make the std deviation = 1 and mean alue to be 0
from sklearn.preprocessing import StandardScaler
from pandas import read_csv
from numpy import set_printoptions

filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] # col names
dataframe = read_csv(filename, names = names)
array = dataframe.values

#now we sepearate array into input and output components
X = array[:, 0:8]
Y = array[8, :]
scaler = StandardScaler().fit(X)
rescaledX = scaler.fit_transform(X)

#summarize trnaform data
set_printoptions(precision = 2)
print(rescaledX[0:5 ,:])



[[ 0.64  0.85  0.15  0.91 -0.69  0.2   0.47  1.43]
 [-0.84 -1.12 -0.16  0.53 -0.69 -0.68 -0.37 -0.19]
 [ 1.23  1.94 -0.26 -1.29 -0.69 -1.1   0.6  -0.11]
 [-0.84 -1.   -0.16  0.15  0.12 -0.49 -0.92 -1.04]
 [-1.14  0.5  -1.5   0.91  0.77  1.41  5.48 -0.02]]


In [42]:
#Normalizing data . This method is used as a pre processing method for sparse data set 
from sklearn.preprocessing import Normalizer
from pandas import read_csv
from numpy import set_printoptions

filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] # col names
dataframe = read_csv(filename, names = names)
array = dataframe.values

#separate array into input adn output components
X = array[:, 0:8]
Y = array[8, :]
scaler = Normalizer().fit(X)
normalizedX = scaler.fit_transform(X)

set_printoptions(precision = 3)
print(normalizedX[0:5,:]) 




[[ 0.034  0.828  0.403  0.196  0.     0.188  0.004  0.28 ]
 [ 0.008  0.716  0.556  0.244  0.     0.224  0.003  0.261]
 [ 0.04   0.924  0.323  0.     0.     0.118  0.003  0.162]
 [ 0.007  0.588  0.436  0.152  0.622  0.186  0.001  0.139]
 [ 0.     0.596  0.174  0.152  0.731  0.188  0.01   0.144]]


In [41]:
#Binarizing data !!!  making data binary cero y un

from sklearn.preprocessing import Binarizer
from pandas import read_csv
from numpy import set_printoptions

filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] # col names
dataframe = read_csv(filename, names = names)
array = dataframe.values

X = array[:, 0:8]
Y = array[8, :]
binarizer = Binarizer(threshold = 0.0).fit(X)
binarizedX = binarizer.transform(X)

set_printoptions(precision = 3)
print(binarizedX[0:5,:]) 



[[ 1.  1.  1.  1.  0.  1.  1.  1.]
 [ 1.  1.  1.  1.  0.  1.  1.  1.]
 [ 1.  1.  1.  0.  0.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.]]
